### ISSUE TITLE
The kernel appears to have died. It will restart automatically.

### ISSUE THREAD

**Issue by nguyenanht** [MattsProjects/PyPylonSamples#1]
Hello, 

Thank you for your samples. I tried to execute your code PyPylonOpenCV.py with python 3.6 with jupyter notebook and with python console.
It seems to crash my kernel at this line : 
`camera = pylon.InstantCamera(pylon.TlFactory.GetInstance().CreateFirstDevice(info))`

The issue when I tried to execute CreateFirstDevice() is restarting my kernel. 
The message is : 

> 

 The kernel appears to have died. It will restart automatically.

> 

Do you know how can I solve this problem ?

Thank you.

Best regards,

Johnathan

**Comment by MattsProjects** [comment]
Hi Johnathan,
Sorry, but I have no experience with jupyter notebook, which appears to be the one throwing this error (from a google search). Some forums point to memory issues?
I can say though that CreateFirstDevice(info) will find the camera specified by the 'info' object, which in the sample specifies a camera with serial number "21734321" (you can just use CreateFirstDevice() without the info to connect to truly the first device it finds on your system).
If the info-specified device isn't found (it won't be because that's my camera 😀 ), pylon will throw an error saying no devices are found.
I guess maybe jupyter doesn't like that, or doesn't like that the program ends there? There's of course some unwinding of stacks, freeing of memory, etc. during shutdown.
